### ISSUE TITLE
Changing taxonomic level in crosstab

### ISSUE THREAD

**Issue by marbotte** [kamapu/vegtable#43]
Would it be possible to change the taxonomic level in the function crosstab, as an argument

**Comment by kamapu** [comment]
Hi, @marbotte. You can still edit your request. For it, you don't need a minimal example (I already understand it). I will set it as priority.

**Comment by kamapu** [comment]
A possible strategy is to insert an argument **levels**, which is passed to `taxlist::merge_taxa()` (same argument's name) and run this function, if not missing.

**Comment by marbotte** [comment]
Ok, nice! Thanks @kamapu ! Please let me know whether I can help with that. I am willing to put my hands in that if needed! I won't be quick, but I can work on a branch doing specifically that if it helps!

**Comment by kamapu** [comment]
OK, I see, I need first to work at **taxlist**: https://github.com/ropensci/taxlist/issues/40
